### ISSUE TITLE
Multi_asset safety check in spec, LIGO

### ISSUE THREAD

**Issue by tomjack** [tqtezos/smart-contracts#17]
Hello!

The multi asset spec mentions "safety check" for token receivers in a couple places, and also uses the language "MUST implement" -- in particular regarding the `multi_token_receiver` interface.

What is the meaning of this, exactly? It is not very clear.

The `multi_token_receiver` interface is defined like this as a LIGO variant:

```
type multi_token_receiver =
  | On_multi_tokens_received of on_multi_tokens_received_param
```

The variant has only one case, so in LIGO, the type `multi_token_receiver` is compiled the same way as `on_multi_tokens_received_param` -- as a tree of `pair` types.

(I think, at the moment, you should not write Michelson interface specifications using LIGO types!)

In the draft LIGO implementation, we have code like this:

```
  let receiver : multi_token_receiver contract = 
    Operation.get_contract param.to_ in
```

(Recall `to_ : address` in the transfer parameter.)

In the compiled Michelson, this shows up as:

```
CONTRACT (pair (pair (list (pair nat nat)) bytes) (pair (option address) address))
IF_NONE { PUSH string "bad address for get_contract" ; FAILWITH } {} ;
```

This seems to have some interesting consequences.

Most importantly, I believe this means that passing a `to_` address with an entry point (intending to transfer to a receiver who implements %on_multi_tokens_received as well as other entrypoints) will result in locked tokens. Token receivers will require proxy contracts,

It is possible I am confused? It is late.

┆Created By: tqbot

**Comment by emishur** [comment]
After deliberation, I decided not to change receiver interface, but update the spec only.
There are multiple scenarios and/or use cases how token management behind a receiver contract can be implemented (from simple automatic forwarding of received tokens to an elaborate operator management). We do not want to lock down on only on one of the possible scenarios, since this contract spec focuses on transfer logic and leaves other essential aspects out of scope to be customized for particular business cases.

**Comment by tomjack** [comment]
OK.

I don't understand how any other scenario is possible -- even if you forward the tokens, you must forward them to a contract which will immediately (or has already) done `Add_operator`.

I believe there is still the original issue that the safety check will allow tokens to be locked forever if an address with an entry point is given as the destination/to_.

Hopefully people who would do that will test it before trying it with tokens which matter, though. :)

Both of these issues (and at least one other I didn't mention, which is less important) would be solved, I think, by using `CONTRACT %on_multi_tokens_received ...` -- on one hand, a contract could have other entrypoints, on the other hand, the 'safety check' would better fulfill its intended purpose.

**Comment by emishur** [comment]
@tomjack There is a PR (https://github.com/tqtezos/smart-contracts/pull/18) to explain what are possible scenarios are. But it looks you found it already 🙂

**Comment by tomjack** [comment]
This is largely fixed now (in the implementation at least -- spec is still not very clear) with the use of `CONTRACT %on_multi_tokens_received ...`.
